
class circuit:

    #Constructors
    def __init__(self):
        # a list of lines. The line should be in order
        self.connection = []

    #connect lines in parallel
    def connectInParallel(self, *lines):
        for l in lines:
            self.connection.append(l)

    #connect lines in series
    def connectInSeries(self, *lines):
        for l in lines:
            self.connection.extend(l.elements)

    # There will be more methods to add a new line, or change the order of a line

    # mutators

    # this method converts the data to a valid SchemdDraw Program
    # 'RunAddress' is where Run.py is located; 'ImageName' is the filename of the generated image'
    def writeDocument(self, RunAddress, ImageName):
        file = open(RunAddress, 'w')
        file.write('# The following code is generated by Main.py\n'
                   'import SchemDraw as schem\n'                  #import the SchemeDraw package
                   'import SchemDraw.elements as e\n'             #and elements
                   'd = schem.Drawing()\n'                        #Default setting . . .
                   'd.add(e.LINE, d = \'right\')\n'
                    + str(self.connection[0]) + '\n'              #First line
                   'd.draw()\n'                                   #If Run.txt is ran with Jupyter Notebook, this allows the image to show within the notebook
                   'd.save(\'' + ImageName + '\')\n')             #Save the image

